### ISSUE TITLE
Thumbnails/Storage sometimes not working due to Django SuspiciousFileOperation

### ISSUE THREAD

**Issue by ZuitAMB** [GeoNode/geonode#13216]
## Expected Behavior
When uploading datasets, thumbnails should be uploaded, processed and later shown correctly.

## Actual Behavior
The Thumbnail cannot be created, which leads to it not being shown/rendered later on.

## Steps to Reproduce the Problem

  1. (Optional) use relative paths for STATIC ROOT etc.
  2. Create/Upload a dataset
  3. See if a thumbnail is present

## Specifications

  - GeoNode version: 4.4.3 (also master)
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): docker
  - Platform: Azure Container Apps
  - Additional details: Stacktrace, Links, Related Tickets/Issues

## Example Stack Trace taken from Celery
```shell
Detected path traversal attempt in '/usr/src/odp/volumes/statics/uploaded/thumbs/dataset-92530cb7-36a2-4c4e-be54-73d6292d292c-thumb-185ffc02-3e51-4b53-9ddc-3dde178a1309.jpg'
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/geonode/base/models.py", line 1570, in save_thumbnail
storage_manager.save(storage_manager.path(upload_path), img)
File "/usr/local/lib/python3.10/dist-packages/geonode/storage/manager.py", line 161, in save
return self._concrete_storage_manager.save(name, content, max_length=max_length)
File "/usr/local/lib/python3.10/dist-packages/geonode/storage/manager.py", line 300, in save
return self._fsm.save(name, content, max_length=max_length)
File "/usr/local/lib/python3.10/dist-packages/django/core/files/storage/base.py", line 41, in save
validate_file_name(name, allow_relative_path=True)
File "/usr/local/lib/python3.10/dist-packages/django/core/files/utils.py", line 17, in validate_file_name
raise SuspiciousFileOperation(


[2025-05-27 12:35:54,568: ERROR/ForkPoolWorker-230] Detected path traversal attempt in '/usr/src/odp/volumes/statics/uploaded/thumbs/dataset-92530cb7-36a2-4c4e-be54-73d6292d292c-thumb-185ffc02-3e51-4b53-9ddc-3dde178a1309.jpg'
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/geonode/base/models.py", line 1570, in save_thumbnail
storage_manager.save(storage_manager.path(upload_path), img)
File "/usr/local/lib/python3.10/dist-packages/geonode/storage/manager.py", line 161, in save
return self._concrete_storage_manager.save(name, content, max_length=max_length)
File "/usr/local/lib/python3.10/dist-packages/geonode/storage/manager.py", line 300, in save
return self._fsm.save(name, content, max_length=max_length)
File "/usr/local/lib/python3.10/dist-packages/django/core/files/storage/base.py", line 41, in save
validate_file_name(name, allow_relative_path=True)
django.core.exceptions.SuspiciousFileOperation: Detected path traversal attempt in '/usr/src/odp/volumes/statics/uploaded/thumbs/dataset-92530cb7-36a2-4c4e-be54-73d6292d292c-thumb-185ffc02-3e51-4b53-9ddc-3dde178a1309.jpg'
File "/usr/local/lib/python3.10/dist-packages/django/core/files/utils.py", line 17, in validate_file_name
raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: Detected path traversal attempt in '/usr/src/odp/volumes/statics/uploaded/thumbs/dataset-92530cb7-36a2-4c4e-be54-73d6292d292c-thumb-185ffc02-3e51-4b53-9ddc-3dde178a1309.jpg'
``` 
## Relevant code fragments
https://github.com/GeoNode/geonode/blob/03a6578139be2aae88860af016f169737aa5785b/geonode/base/models.py#L1564
https://github.com/GeoNode/geonode/blob/03a6578139be2aae88860af016f169737aa5785b/geonode/storage/manager.py#L161
https://github.com/GeoNode/geonode/blob/03a6578139be2aae88860af016f169737aa5785b/geonode/storage/manager.py#L300
https://github.com/django/django/blob/ad28db666e0884b658f5e240c3d7ee1362688ba1/django/core/files/storage/base.py#L41
https://github.com/django/django/blob/ad28db666e0884b658f5e240c3d7ee1362688ba1/django/core/files/utils.py#L18

## First Analysis on possible causes
Exception is thrown in the Django Package here: https://github.com/django/django/blob/ad28db666e0884b658f5e240c3d7ee1362688ba1/django/core/files/utils.py#L18 because it gets passed an absolute path.

To fix it, we moved to using relative paths for STATIC_ROOT, MEDIA_ROOT etc.:
```shell
STATIC_ROOT=volumes/statics/static/
MEDIA_ROOT=volumes/statics/uploaded/
``` 
and mounted to the relative path in the working directory. (Works fine)

However, we still get some of those exceptions.

Could it be related to the path being converted to an absolute one during processing around here?:
https://github.com/GeoNode/geonode/blob/03a6578139be2aae88860af016f169737aa5785b/geonode/base/models.py#L1546-L1564

## Related tickets/exceptions
https://github.com/GeoNode/geonode/issues/12862

**Comment by giohappy** [comment]
@ZuitAMB, we also noticed that, and we have planned to investigate it. I'm not sure the solution of using relative paths is ok, but will consider it.

**Comment by ZuitAMB** [comment]
@giohappy great! :) We tried the workaround of using relative paths, but it seemed, that they were converted to absolute ones in the process and we still got those exceptions once in a while.
Other solutions would be great as well of course.

**Comment by mattiagiupponi** [comment]
So the reason is that django (i suppose from 4.2 version) allow relative paths during the file saving in the default manager and when the path provided is absolute, it raise a [SuspiciousFileOperation](https://github.com/django/django/blob/87175d270aec969d3cad4bad1abf45e07302d795/django/core/files/utils.py#L12-L19) error:

```python
if allow_relative_path:
        # Ensure that name can be treated as a pure posix path, i.e. Unix
        # style (with forward slashes).
        path = pathlib.PurePosixPath(str(name).replace("\\", "/"))
        if path.is_absolute() or ".." in path.parts:
            raise SuspiciousFileOperation(
                "Detected path traversal attempt in '%s'" % name
            )
```

GeoNode give the absolute path during the save of the thumbnail (the function `.path` return the aboslute path of the file)

https://github.com/GeoNode/geonode/blob/dc4a513b5dfe066fef31583e2ea9fe0fd9dc1e69/geonode/base/models.py#L1564

So the solution here is to remove the .path function during the save of the thumbnail and django does not raise the error anymore.
This will not create any issue for two reasons:
- Django use by default the MEDIA_ROOT to decide where to save the file itself
- Few lines before, GeoNode already save the file without using the `.path` [function](https://github.com/GeoNode/geonode/blob/dc4a513b5dfe066fef31583e2ea9fe0fd9dc1e69/geonode/base/models.py#L1547)

The changes will be something like the following:

```python
with open(tmp_location, "rb+") as img:
    # Saving the img via storage manager
    storage_manager.save(upload_path, img)
```

**Comment by mattiagiupponi** [comment]
PR open https://github.com/GeoNode/geonode/pull/13248

**Comment by giohappy** [comment]
@mattiagiupponi le'ts backport this to 4.4.x

**Comment by mattiagiupponi** [comment]
done, i'll close the issue.
@ZuitAMB if you have time, can you please verify that everything works also on your side?

**Comment by ZuitAMB** [comment]
Thanks a lot! This should fix our issues in combination with the relative paths. We will run our testsuite again and would reopen this issue, in case it didn't fix it completely :)

**Comment by ZuitAMB** [comment]
We haven't seen SuspiciousFileExceptions during our latest run. Works as intended!

**Comment by mattiagiupponi** [comment]
great, thanks for the feedback @ZuitAMB 💯
