### ISSUE TITLE
Error when adding a new feature in demo dev server

### ISSUE THREAD

**Issue by bermud** [GeoNode/geonode#6063]
## Expected Behavior
We should be able to add a new feature with data via the GeoNode editing interface as explained here: https://docs.geonode.org/en/master/usage/managing_layers/layer_editing.html

## Actual Behavior
I created a new layer as well as uploaded a shapefile via the user interface. Tried to add a new feature with some attributes and in both cases it failed. See error on the top right. 

![image](https://user-images.githubusercontent.com/3738898/81351780-17ac9500-9093-11ea-990f-738830d4664f.png)

## Steps to Reproduce the Problem

  1.  
  2.
  3.

## Specifications

  - GeoNode version: https://dev.geonode.geo-solutions.it/ - Tested on May 7th 6:00-6:30 PM Eastern time
  - Installation method 
  - Platform:
  - Additional details:

**Comment by afabiani** [comment]
The GeoServer was not updated. This is now fixed. @bermud can you please try again?

**Comment by bermud** [comment]
I just checked (May 8 - 2:25 Eastern). I tried to update the California state with the latest data. I still get the error. 

![image](https://user-images.githubusercontent.com/3738898/81436692-e6d26b80-9137-11ea-918f-3de5e290e1ee.png)

**Comment by afabiani** [comment]
Don't know exactly what happened, but I was actually able to edit the data

![image](https://user-images.githubusercontent.com/1278021/81483855-6c8e0e00-9241-11ea-9d0b-ba49c41a4967.png)

probably a wrong input on a field?

**Comment by afabiani** [comment]
Oh, taking a look at the request sent to the server I discovered this

https://dev.geonode.geo-solutions.it/gs/ows?access_token=None

It seems like that sometimes the editor is not able to retrieve the access_token.
I will further investigate this.

**Comment by afabiani** [comment]
Ok, so it seems like the session expired but GeoNode has not forced logout.

In order to fix this issue try to logout and login again.

I will investigate the other one.

**Comment by afabiani** [comment]
That should be fixed now.

**Comment by bermud** [comment]
@afabiani, thank you for checking this out.

I see my user was deleted :-). Registering again and creating a new layer worked. 

Now, in edit mode it's not clear how to put the date. I suggest to add a date picker in editing mode.

Creating a date like this did not work: 05/11/2020.

This is the error that popped up in the upper right screen. 


```
An error occured with saving operation
java.lang.RuntimeException: Parsing failed for last-updated: java.lang.IllegalArgumentException: Failed to parse dateTime 05/11/2020 at:/11/2020 Parsing failed for last-updated: java.lang.IllegalArgumentException: Failed to parse dateTime 05/11/2020 at:/11/2020 Failed to parse dateTime 05/11/2020 at:/11/2020
```

We also need to put an extra 'r' in the error message: "occurred" instead of 'occured'

**Comment by afabiani** [comment]
@bermud I guess this is an issue of MapStore.
Let's eventually create another issue for that last point.

**Comment by gabrielbonifaz** [comment]
Hi @afabiani, I have the same issue with geonode core, could you post how you fix it. I´ll appreciate it

**Comment by afabiani** [comment]
@gabrielbonifaz you need to do two updates:

1. Update your GeoServer with the latest WAR (same version) available [here](https://build.geo-solutions.it/geonode/geoserver/latest/)

2. Update your GeoNode to the latest commits

**Comment by gabrielbonifaz** [comment]
@afabiani Thank you!
